dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  equatable: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.19.3
  get_it: ^6.0.0
  http: ^0.12.2
  injectable: ^1.2.0
  intl: ^0.17.0
  keyboard_actions: ^3.2.0
  page_transition: ^2.0.1
  responsive_builder: ^0.3.0
  retrofit: ^1.3.1+1
  shared_preferences: ^0.5.6
  split_view: ^3.1.0
description: A new Flutter application.
dev_dependencies:
  bloc_test: ^7.1.0
  build_runner: null
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.0.4
  lint: ^1.1.1
  mockito: ^4.1.1
  retrofit_generator: ^1.3.8+1
environment:
  sdk: '>=2.8.4 <3.0.0'
flutter:
  assets:
  - config/
  - assets/svg_images/light/ar/
  - assets/svg_images/light/en/
  - assets/images/logo.png
  - assets/svg_images/dark/en/
  - assets/
  - assets/svg_images/dark/ar/
  fonts:
  - family: Poppins
    fonts:
    - asset: fonts/Poppins-Regular.ttf
    - asset: fonts/Poppins-Bold.ttf
      weight: 700
    - asset: fonts/Poppins-SemiBold.ttf
      weight: 500
  - family: Cairo
    fonts:
    - asset: fonts/Cairo-Regular.ttf
    - asset: fonts/Cairo-Bold.ttf
      weight: 700
    - asset: fonts/Cairo-SemiBold.ttf
      weight: 500
  uses-material-design: true
name: rent_ready_app
publish_to: none
version: 1.0.0+1
